channels:
- defaults
dependencies:
- python=3.6.6
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/19054820
  - azureml-defaults==0.1.0.19054820
  - azureml-pipeline-wrapper==0.1.0.19054820
name: project_environment
